### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by Mike-E-angelo** [picrap/DNParser#1]
Not an issue, but I wanted to thank you for posting this to NuGet!  That was my first response when I saw the answer for the CodeProject link here:
http://stackoverflow.com/questions/7688445/extract-common-name-from-distinguished-name

Thanks again. :)  Please feel free to close this item whenever you can.

**Comment by picrap** [comment]
:smile: 
The original author, Pete Everett, did a pretty good job, he's the one we should have thanked.
