### ISSUE TITLE
Create .NET Standard version

### ISSUE THREAD

**Issue by thomaswurtz** [picrap/DNParser#2]
Now that .NET Core is out it would be nice with a .NET Standard version of this library.
It looks like it should be pretty straight forward since no legacy libraries are use from what I can see.

Is this something that you could fix? 🙂

**Comment by picrap** [comment]
Hi Thomas,

it sure would! The best would be a mixed version, since I use the library in my own project and I'm currently stuck with .NET 4.0 (this one not being supported by any .NET standard version).

**Comment by thomaswurtz** [comment]
Hi Pascal,
Ok that sounds like a good approach. I started a PR as you noticed 🙂. Its updated with net4.0 support as well.
