### ISSUE TITLE
DNParser 1.3 NuGet strong name

### ISSUE THREAD

**Issue by romanrotter** [picrap/DNParser#4]
Hello,

since version 1.3 the assembly distributed through nuget (https://www.nuget.org/packages/DNParser/) is not signed. 
Do you plan to release also signed nuget package, please?

Thank you,
Roman

**Comment by picrap** [comment]
Ouch! Thanks for pointing this out. It was a simple mistake. It should be fixed in 1.3.1. Can you confirm?

**Comment by romanrotter** [comment]
Great, it was fast! It's working now :)
